export const FETCH_BLOCK = 'FETCH_BLOCK';
export const FETCH_BLOCKS = 'FETCH_BLOCKS';
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const FETCH_GRAPH = 'FETCH_GRAPH';
export const FETCH_LAST_BLOCKS = 'FETCH_LAST_BLOCKS';
export const FETCH_LAST_TRANSACTIONS = 'FETCH_LAST_TRANSACTIONS';
